name: Medicine Malaysia
favicon: null
layout_spectrum: 0.7544
typography_spectrum: 0.33063027169555426
title: Medicine Malaysia
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#78193d'
    - '#011d59'
    - '#ffffff'
    - '#c5a4b0'
    - '#95536c'
  brandStrength: 0.5
  lightness: 0.5802176750730723
  saturation: 0.625
  rhythmicContrast: 0.6231000865809619
purpose: []
