name: Medicine Malaysia
favicon: null
layout_spectrum: 0.9638414832297713
typography_spectrum: 0.33063027169555426
title: Medicine Malaysia
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8239807733334601
  lightness: 0.5802176750730723
  saturation: 0.5067321548704058
  rhythmicContrast: 0.6231000865809619
purpose: []
